version: "3.2"
services:
  wordpress:
    image: wordpress:5.1.0-php7.1-apache
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - backend
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpass
      WORDPRESS_DB_NAME: vincent_db
    volumes:
      - ./public_html/wp-content:/var/www/html/wp-content

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    networks:
      - backend
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: vincent_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: dbpass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - mysql
    external_links:
    - mysql:mysql
    ports:
    - "8000:80"
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: dbpass
      PMA_HOST: mysql
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: